name: Alpaca Wheel Bot

on:
  schedule:
    # ---- times are UTC ----
    - cron: '30 14 * * 1-5'   # 08:30 MDT (market open)
    - cron: '00 20 * * 1-5'   # 14:00 MDT (mid-session)
  workflow_dispatch:

jobs:
  wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python wheel_bot.py
        env:
          ALPACA_KEY_ID:     ${{ secrets.ALPACA_KEY_ID }}
          ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
          ALPACA_PAPER:      ${{ secrets.ALPACA_PAPER }}
